### ISSUE TITLE
Using server.babel.js rather than building each server.

### ISSUE THREAD

**Issue by ncrmro** [denvned/isomorphic-relay-boilerplate#5]
I currently have it working (I think?) where the backend and proxy both work with entries like this. 

server.babel.js

```
require('babel-register');
require('babel-polyfill');
require('./index');
```

backend package.json

```
{
  "private": true,
  "dependencies": {
    "express-graphql": "^0.4.9",
    "graphql": "^0.4.18",
    "graphql-relay": "^0.3.6"
  },
  "scripts": {
    "postinstall": "npm run update-schema",
    "start": "node ./src/server.babel.js",
    "update-schema": "babel-node scripts/updateSchema.js"
  }
}


```

And working on getting the frontend working. Would you be open to a pull request like this?

**Comment by denvned** [comment]
Isn't that the same as just `"start": "babel-node src"`?

**Comment by ncrmro** [comment]
After looking into it your definitely right. Thanks for the info! Closing.
